config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do

  get 'groups/new'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  root 'events#index'


  get 'search', to: 'events#search'

  get 'users/:id/portfolio', to: 'users#portfolio'
  get 'users/:id/joiningEvent', to: 'users#joiningEvent',as: "user_joiningEvent"

  resources :events do
    patch :toggle_status
    collection do
        get 'confirm'
      end
  end
  resources :users
  resources :user_events, only: [:create, :destroy]
  resources :event_category, only: [:create, :destroy]
  get 'category/:name', to: 'category#show', as: 'category'
  get 'categories', to: 'category#index', as: 'categories'
  resources :groups
  resources :user_groups,only: [:create, :destroy]


  mount ActionCable.server => '/cable'
end

app/models/category.rb
# -*- encoding : utf-8 -*-
class Category < ApplicationRecord
  has_many :event_categories, dependent: :destroy
  has_many :event, through: :event_categories
  validates :name, presence: true
end

app/models/event.rb
# -*- encoding : utf-8 -*-
class Event < ApplicationRecord
 validates :title, presence: true
 validates :started_at, presence: true
 validates :location, presence: true

 has_many :event_categories, dependent: :destroy
 has_many :categories, through: :event_categories

 has_many :user_events, dependent: :destroy
 has_many :users, through: :user_events

 has_many :upload_files, dependent: :destroy

 enum status: { draft: 0, published: 1 }
 validates :status, inclusion: { in: Event.statuses.keys }

 Geocoder.configure(language: :ja)
 geocoded_by :address,latitude: :lat, longitude: :lon
 after_validation :geocode, if: :address_changed?


 def toggle_status!
     if draft?
       published!
     else
       draft!
     end
   end


 # geocoded_by :address
 # after_validation :geocode

 # カテゴリーを加える
 def add_category(category)
  categories << category
 end
  # イベントに登録されているカテゴリーの削除
 def delete_category(category)
   event_categories.find_by(category: category.id).destroy
 end
 # イベントにそのカテゴリーが含まれるか確認する
 def category_include?(category)
   categories.include?(category)
 end
end

app/models/group.rb
# -*- encoding : utf-8 -*-
class Group < ApplicationRecord
  validates :name, presence: true
  validates :description,presence: true
  validates :image,presence: true
  has_many :user_groups
  has_many :users,through: :user_groups
  mount_uploader :image, ImageUploader


end

app/models/internship.rb
# -*- encoding : utf-8 -*-
class Internship < ApplicationRecord
end

app/models/job.rb
# -*- encoding : utf-8 -*-
class Job < ApplicationRecord

end

app/models/job_category.rb
# -*- encoding : utf-8 -*-
class JobCategory < ApplicationRecord
  belongs_to :job
  belongs_to :category
end

app/models/message.rb
# -*- encoding : utf-8 -*-
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/post.rb
# -*- encoding : utf-8 -*-
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
# -*- encoding : utf-8 -*-
class Room < ApplicationRecord
   validates :name, presence: true

  has_many :posts

  has_many :user_rooms
  has_many :users, through: :user_rooms
end

app/models/upload_file.rb
# -*- encoding : utf-8 -*-
class UploadFile < ApplicationRecord 
  belongs_to :events
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         :omniauth_providers => [:google_oauth2,:twitter]
  validates :name, presence: true
  validates :email, presence: true

  has_many :user_jobs, dependent: :destroy
  has_many :jobs, through: :user_jobs

  has_many :user_lessons, dependent: :destroy
  has_many :lessons, through: :user_lessons

  has_many :user_events, dependent: :destroy
  has_many :events, through: :user_events

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = User.dummy_email(auth)
      user.password = Devise.friendly_token[0,20]
      user.image = auth.info.image.gsub("_normal","") if user.provider == "twitter"
      user.image = auth.info.image.gsub("_normal","") if user.provider =="google_oauth2"
      user.name =  auth.info.name
      end
  end



   mount_uploader :image, ImageUploader
   has_many :user_rooms
   has_many :rooms, through: :user_rooms
   has_many :posts
   has_many :user_groups
   has_many :groups,through: :user_groups

  # イベントに参加する
  def event_join(event)
    events << event
  end
   # イベントの参加をキャンセルする
  def event_unjoin(event)
    user_events.find_by(event_id: event.id).destroy
  end
  # ユーザーがイベントに参加予定か確認する
  def event_will_user_join?(event)
    events.include?(event)
  end



  def groupsJoin(group)
    groups << group

  end

  def groupsUnjoin(group)
    user_groups.find_by(group_id: group.id).destroy

  end

  def groupJoining?(group)
    groups.include?(group)
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/models/user_event.rb
# -*- encoding : utf-8 -*-
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user_group.rb
# -*- encoding : utf-8 -*-
class UserGroup < ApplicationRecord

  belongs_to :user
  belongs_to :group
  validates :user_id,presence: true
  validates :group_id,presence: true

end

app/models/user_job.rb
# -*- encoding : utf-8 -*-
class UserJob < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/models/user_lesson.rb
# -*- encoding : utf-8 -*-
class UserLesson < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
end

app/models/user_room.rb
# -*- encoding : utf-8 -*-
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/groups_controller.rb
# -*- encoding : utf-8 -*-
class GroupsController < ApplicationController
  def index
    @groups = Group.all

  end

  def show
    @group = Group.find(params[:id])
    @users = @group.users

  end


  def new
    @group = Group.new

  end

  def create
    @group = Group.new(group_params)
    @group.owner=current_user.id#グループを作成した人が管理者になる
    if @group.save
      redirect_to groups_path,notice: "コミュニティを作成しました"
    else
      flash[:danger]= "作成できませんでした"
      render :new
    end
  end


  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:success] = "更新しました"
      redirect_to @group
    else
      render 'group'
    end
  end


  def destroy
    @group = Group.find(parmas[:id])
    @group.destroy
    redirect_to root, notice: "グループを削除しました"
  end

  private
  def group_params
    params.require(:group).permit(:name,:description,:image)
  end

end

app/helpers/devise_helper.rb
# -*- encoding : utf-8 -*-
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/events_helper.rb
# -*- encoding : utf-8 -*-
module EventsHelper
end

app/helpers/groups_helper.rb
# -*- encoding : utf-8 -*-
module GroupsHelper
end

app/helpers/jobs_helper.rb
# -*- encoding : utf-8 -*-
module JobsHelper
end

app/helpers/rooms_helper.rb
# -*- encoding : utf-8 -*-
module RoomsHelper
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper 

end

app/views/groups/index.html.erb
<div class="communityList_wrapper">
  <div class="communityList_left">
    <h2>コミュニティ一覧</h2>

    <div class="communityList_list">
      <% @groups.each do |group|  %>
        <div class="communityList_list_item">
          <img src="paper.jpg" alt="">
              <div class="communityList_list_item_text">
                <h3><%= link_to group.name, group_path(group),class: "communityList_list_item_text"%></h3>
              <div class="communityList_list_item_tags">
                <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
                <a href="#"><i class="material-icons">local_offer</i>React</a>
                <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
                <a href="#"><i class="material-icons">local_offer</i>Redux</a>
              </div>
                <p><%= group.description%> 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
            </div>
        </div>
    <% end %>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

      <div class="communityList_list_item">
        <img src="paper.jpg" alt="">
        <div class="communityList_list_item_text">
          <h3>もくもく寺</h3>
          <div class="communityList_list_item_tags">
            <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
            <a href="#"><i class="material-icons">local_offer</i>React</a>
            <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
            <a href="#"><i class="material-icons">local_offer</i>Redux</a>
          </div>
          <p>恵比寿地区で開催するJavaScript講座のグループです。 検討中の講座リスト： Javascript基礎 Node.js/Express基礎 React基礎 Redux基礎</p>
        </div>
      </div>

    </div>
  </div>

  <div class="communityList_right">
    <div class="communityList_categories_wrapper">
      <h3>タグ検索</h3>
      <div class="communityList_categories">
        <ul>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
          <li><a href="#"><i class="material-icons">local_offer</i>Node.js</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="community-form-wrapper">

    <%= form_with model: @group ,local: true do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, placeholder: "タイトル", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :詳細%>
        <%= form.text_area :description, placeholder: "詳細", class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label :イメージ画像 %><br/>
        <%= form.file_field :image %>
      </div>

      <%= form.submit "コミュニティを作成する", class: "btn btn-info" %>
    <% end %>


  </div>
</div>

app/views/groups/show.html.erb
        <!-- ここから使用 -->
        <div class="community_container">
          <div class="community_headerImage_wrapper">
            <div class="community_headerImage" >
              </div>
          </div>

          <div class="community_profile_wrapper">
            <div class="community_profile">
              <img class="community_profile_image" src=<%= @group.image%> alt="">
              <div class="community_profile_text">
                <h1><%= @group.name %></h1>
                <div class="community_profile_tags">
                  <a href="#"><i class="material-icons">local_offer</i>Node.js</a>
                  <a href="#"><i class="material-icons">local_offer</i>React</a>
                  <a href="#"><i class="material-icons">local_offer</i>Javascript</a>
                  <a href="#"><i class="material-icons">local_offer</i>Redux</a>
                </div>
              </div>
            </div>
          </div>

          <div class="community_main_wrapper">
            <div class="community_main_left">

              <div class="community_description">
                <h2>コミュニティの説明</h2>
                <div class="community_description_text">
                  <p><%= @group.description %><br><br>
                    検討中の講座リスト：<br><br>
                    Javascript基礎<br>
                    Node.js/Express基礎<br>
                    React基礎<br>
                    Redux基礎<br>
                  </p>
                </div>
              </div>

              <div class="community_main_event">
                <div class="community_event_status">
                  <h2>次回のイベント</h2>
                </div>

                <div class="community_event">
                  <div class="community_event_image">
                    <img src="blueSmoke.jpg" alt="">
                  </div>
                  <div class="community_event_separator"></div>
                  <div class="community_event_text">
                    <h2>Ruby on Rail勉強会</h2>
                    <p class="community_event_description">Ruby使ってみんなでもくもく会</p>
                    <div class="community_event_info">
                      <p class="community_event_place"><i class="material-icons">room</i>GVH Osaka</p>
                      <img src="logo.png" alt="owner_img">
                      <p class="community_event_organizer">株式会社 Gude</p>
                    </div>
                    <div class="community_event_time">
                      <p>2019年</p>
                      <p>12月</p>
                      <p>12日</p>
                      <p>18:00～</p>
                    </div>
                  </div>
                </div>

                <div class="community_event">
                  <div class="community_event_image">
                    <img src="blueSmoke.jpg" alt="">
                  </div>
                  <div class="community_event_separator"></div>
                  <div class="community_event_text">
                    <h2>Ruby on Rail勉強会</h2>
                    <p class="community_event_description">Ruby使ってみんなでもくもく会</p>
                    <div class="community_event_info">
                      <p class="community_event_place"><i class="material-icons">room</i>GVH Osaka</p>
                      <img src="logo.png" alt="owner_img">
                      <p class="community_event_organizer">株式会社 Gude</p>
                    </div>
                    <div class="community_event_time">
                      <p>2019年</p>
                      <p>12月</p>
                      <p>12日</p>
                      <p>18:00～</p>
                    </div>
                  </div>
                </div>

                <div class="community_event">
                  <div class="community_event_image">
                    <img src="blueSmoke.jpg" alt="">
                  </div>
                  <div class="community_event_separator"></div>
                  <div class="community_event_text">
                    <h2>Ruby on Rail勉強会</h2>
                    <p class="community_event_description">Ruby使ってみんなでもくもく会</p>
                    <div class="community_event_info">
                      <p class="community_event_place"><i class="material-icons">room</i>GVH Osaka</p>
                      <img src="logo.png" alt="owner_img">
                      <p class="community_event_organizer">株式会社 Gude</p>
                    </div>
                    <div class="community_event_time">
                      <p>2019年</p>
                      <p>12月</p>
                      <p>12日</p>
                      <p>18:00～</p>
                    </div>
                  </div>
                </div>

                <div class="community_event_status">
                  <h2>開催したイベント</h2>
                </div>

                <div class="community_event">
                  <div class="community_event_image">
                    <img src="blueSmoke.jpg" alt="">
                  </div>
                  <div class="community_event_separator"></div>
                  <div class="community_event_text">
                    <h2>Ruby on Rail勉強会</h2>
                    <p class="community_event_description">Ruby使ってみんなでもくもく会</p>
                    <div class="community_event_info">
                      <p class="community_event_place"><i class="material-icons">room</i>GVH Osaka</p>
                      <img src="logo.png" alt="owner_img">
                      <p class="community_event_organizer">株式会社 Gude</p>
                    </div>
                    <div class="community_event_time">
                      <p>2019年</p>
                      <p>12月</p>
                      <p>12日</p>
                      <p>18:00～</p>
                    </div>
                  </div>
                </div>

                <div class="community_event">
                  <div class="community_event_image">
                    <img src="blueSmoke.jpg" alt="">
                  </div>
                  <div class="community_event_separator"></div>
                  <div class="community_event_text">
                    <h2>Ruby on Rail勉強会</h2>
                    <p class="community_event_description">Ruby使ってみんなでもくもく会</p>
                    <div class="community_event_info">
                      <p class="community_event_place"><i class="material-icons">room</i>GVH Osaka</p>
                      <img src="logo.png" alt="owner_img">
                      <p class="community_event_organizer">株式会社 Gude</p>
                    </div>
                    <div class="community_event_time">
                      <p>2019年</p>
                      <p>12月</p>
                      <p>12日</p>
                      <p>18:00～</p>
                    </div>
                  </div>
                </div>

                <div class="community_event">
                  <div class="community_event_image">
                    <img src="blueSmoke.jpg" alt="">
                  </div>
                  <div class="community_event_separator"></div>
                  <div class="community_event_text">
                    <h2>Ruby on Rail勉強会</h2>
                    <p class="community_event_description">Ruby使ってみんなでもくもく会</p>
                    <div class="community_event_info">
                      <p class="community_event_place"><i class="material-icons">room</i>GVH Osaka</p>
                      <img src="logo.png" alt="owner_img">
                      <p class="community_event_organizer">株式会社 Gude</p>
                    </div>
                    <div class="community_event_time">
                      <p>2019年</p>
                      <p>12月</p>
                      <p>12日</p>
                      <p>18:00～</p>
                    </div>
                  </div>
                </div>

              </div>
            </div>

            <div class="community_main_right">
              <div class="community_main_right_inner">
                  <% if current_user.groupJoining?(@group)%>
                  <div><%= form_for(current_user.user_groups.find_by(group_id: @group.id),
                   html: { method: :delete }) do |f| %></div>

                    <%= f.submit "退出",class:"community_main_enterButton"  %>
                  <% end %>
                  <% else %>
                    <%=form_for(current_user.user_groups.build)do |f|%>
                      <div><%= hidden_field_tag :group_id, @group.id %></div>
                      <%=f.submit "参加する", class: "community_main_enterButton" %>
                    <% end %>
                  <% end %>


                <% if @group.owner !=nil %>
                <%=button_to "コミュニティを編集する",edit_group_path,:method => :get %>
                 <% end %>
                <%= button_to "イベント作成", new_event_path, :method => :get  %>
                  <%= button_to "コミュニティ一覧",groups_path,:method => :get %>

                <div class="community_members">
                  <h3>メンバー</h3>


                  <div class="community_members_images">
                    <div class="community_members_images_line">
                      <% @users.each do |user|%>
                        <a href="">
                         <img src=<%=user.image%>>
                        </a>
                        <% end %>

                    </div>
                    <div class="community_members_images_line">

                    </div>
                  </div>
                </div>

                <div class="community_main_links">
                  <h3>リンク</h3>
                  <div class="community_links_bg">
                    <ul>
                      <li><a href="#"><img src="icon_twitter.png" alt="">twitter</a></li>
                      <li><a href="#"><img src="icon_github.png" alt="">GitHub</a></li>
                      <li><a href="#"><img src="icon_youtube.png" alt="">Youtube</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- ここまで使用 -->


    <!-- ここまで使用 -->