config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do

  get 'groups/new'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  root 'events#index'


  get 'search', to: 'events#search'

  get 'users/:id/portfolio', to: 'users#portfolio'
  get 'users/:id/joiningEvent', to: 'users#joiningEvent',as: "user_joiningEvent"

  resources :events do
    patch :toggle_status
    collection do
        get 'confirm'
      end
  end
  resources :users
  resources :user_events, only: [:create, :destroy]
  resources :event_category, only: [:create, :destroy]
  get 'category/:name', to: 'category#show', as: 'category'
  get 'categories', to: 'category#index', as: 'categories'
  resources :groups
  resources :user_groups,only: [:create, :destroy]


  mount ActionCable.server => '/cable'
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         :omniauth_providers => [:google_oauth2,:twitter]
  validates :name, presence: true
  validates :email, presence: true

  has_many :user_jobs, dependent: :destroy
  has_many :jobs, through: :user_jobs

  has_many :user_lessons, dependent: :destroy
  has_many :lessons, through: :user_lessons

  has_many :user_events, dependent: :destroy
  has_many :events, through: :user_events

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = User.dummy_email(auth)
      user.password = Devise.friendly_token[0,20]
      user.image = auth.info.image.gsub("_normal","") if user.provider == "twitter"
      user.image = auth.info.image.gsub("_normal","") if user.provider =="google_oauth2"
      user.name =  auth.info.name
      end
  end



   mount_uploader :image, ImageUploader
   has_many :user_rooms
   has_many :rooms, through: :user_rooms
   has_many :posts
   has_many :user_groups
   has_many :groups,through: :user_groups

  # イベントに参加する
  def event_join(event)
    events << event
  end
   # イベントの参加をキャンセルする
  def event_unjoin(event)
    user_events.find_by(event_id: event.id).destroy
  end
  # ユーザーがイベントに参加予定か確認する
  def event_will_user_join?(event)
    events.include?(event)
  end



  def groupsJoin(group)
    groups << group

  end

  def groupsUnjoin(group)
    user_groups.find_by(group_id: group.id).destroy

  end

  def groupJoining?(group)
    groups.include?(group)
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# -*- encoding : utf-8 -*-
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    callback_from :twitter
  end

  def google_oauth2
   callback_for(:google)
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      #flash[:notice] = I18.t("devise.omniauth_callbacks.success", kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
# -*- encoding : utf-8 -*-
class Users::RegistrationsController < Devise::RegistrationsController

  def profile_edit

  end

  def profile_update
    current_user.assign_attributes(account_update_params)
    if current_user.save
      redirect_to user_path(current_user), notice: "プロフィールを更新しました";
    else
      render 'profile_edit'
    end
  end


  private

    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:name,:email,:image])
    end

end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @events = Event.where(id: @user.events)
    @groups = Group.where(id: @user.groups)
  end

  def portfolio
    @user = User.find(params[:id])
    @events = Event.where(id: @user.events)
  end

  def joiningEvent
    @user = User.find(params[:id])
    @events = Event.where(id: @user.events)
  end



end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper 

end

app/views/users/joiningEvent.html.erb
<div class="events">
  <% last_date = nil  %>
  <% @events.each do |event| %>
    <% event_date =  event.started_at.to_date  %>
    <% if event_date != last_date  %>
      <div class="date_bar">
        <%= l(event_date, format: :long)  %>
      </div>
      <% end %>
      <% last_date = event_date  %>
    <div class="event">
      <div class="event_image">
        <%= link_to(event_path(event)) do %>
          <% if event.image  %>
            <%= image_tag event.image, width: "220px", height: "130xp"  %>
          <% elsif event.site %>
            <div class="site_logo">
              <% if event.site == "doorkeeper" %>
                <%= image_tag "doorkeeper.png", width: "140px", height: "30px" %>
              <% elsif event.site == "connpass" %>
                <%= image_tag("connpass.png", width: "120px", height: "40px") %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="event_detail">
        <%= link_to "#{event.title}",event_path(event), class: "event_title" %>
        <div class="event_site">
        </div>
        <div class ="event_detail_path">
          <%=link_to "詳細" ,event_path, :style=>"color:white;"%>
        </div>
        <div class="event_time">
          <%= l(event.started_at, format: :just_time) %><span>~</span>
        </div>
        <div class="event_address">
          <%= icon "fas", "map-marker-alt" %><%= event.location  %>
        </div>
        <div class="event_owner">
          <p><%= event.owner %></p>
        </div>
      </div>
    </div>
  <% end  %>
  <% if @events.empty? %>
    <h3>参加したイベントはありません</h3>
  <% end  %>
</div>

app/views/users/show.html.erb
<div class="portfolio_wrapper">

      <div class="portfolio_left">

        <div class="portfolio_userScore">
          <div class="portfolio_userScore_userName">
            <img src=<%=current_user.image %> alt="">
            <p><%=current_user.name%></p>
          </div>
          <div class="portfolio_userScore_number">
            <h3><%= icon "", "" %> <%= @events.count %></h3>
            <p>参加イベント数</p>

          </div>
          <div class="portfolio_userScore_level">
            <h3>Lv. <span>53</span></h3>
          </div>
        </div>

        <div class="portfolio_list">
          <h2>ポートフォリオ一覧</h2>
          <div class="portfolio_list_container">

            <div class="portfolio_list_item">
              <img src="paper.jpg" alt="">
              <h3>sample web site </h3>
              <p>はじめてhtml/css/JavaScriptを活用してサンプルページを作成しました。</p>
              <a href="#">https://samplePage.com/sample1</a>
            </div>


          </div>

        </div>

      </div>

      <div class="portfolio_right">

        <div class="portfolio_user">

          <img src=<%=current_user.image%> alt="">
          <h2><%=current_user.name%></h2>
          <p>Ruby on Railsを勉強している関西の学生です。自分でサービス開発ができるようになりたいです。</p>
          <div><p><%=link_to "参加イベント一覧", user_joiningEvent_path, :style=>"color:white;"%></p></div>
          <a href="#" class="portfolio_user_linkToEdit"><div><p>ポートフォリオ編集</p></div></a>
        </div>

        <div class="portfolio_communityList">
          <h2>参加コミュニティ</h2>
          <ul>
            <li>
              <% @groups.each do |group| %>
              <img src="logo.png" alt="">
              <a href="#"><p><%=group.name %></p></a>
            </li>
          
            <% end %>
          </ul>
        </div>
        <%= button_to "コミュニティ一覧",groups_path,:method => :get %>
        <%= button_to "コミュニティを作成する", new_group_path, :method => :get %>
        <%= button_to "イベント作成", new_event_path, :method => :get  %>

      <%= button_to "下書きを見る" ,confirm_events_path,:method => :get%>

      </div>

    </div>