config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do

  get 'groups/new'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  root 'events#index'


  get 'search', to: 'events#search'

  get 'users/:id/portfolio', to: 'users#portfolio'
  get 'users/:id/joiningEvent', to: 'users#joiningEvent',as: "user_joiningEvent"

  resources :events do
    patch :toggle_status
    collection do
        get 'confirm'
      end
  end
  resources :users
  resources :user_events, only: [:create, :destroy]
  resources :event_category, only: [:create, :destroy]
  get 'category/:name', to: 'category#show', as: 'category'
  get 'categories', to: 'category#index', as: 'categories'
  resources :groups
  resources :user_groups,only: [:create, :destroy]


  mount ActionCable.server => '/cable'
end

app/models/event.rb
# -*- encoding : utf-8 -*-
class Event < ApplicationRecord
 validates :title, presence: true
 validates :started_at, presence: true
 validates :location, presence: true

 has_many :event_categories, dependent: :destroy
 has_many :categories, through: :event_categories

 has_many :user_events, dependent: :destroy
 has_many :users, through: :user_events

 has_many :upload_files, dependent: :destroy

 enum status: { draft: 0, published: 1 }
 validates :status, inclusion: { in: Event.statuses.keys }

 Geocoder.configure(language: :ja)
 geocoded_by :address,latitude: :lat, longitude: :lon
 after_validation :geocode, if: :address_changed?


 def toggle_status!
     if draft?
       published!
     else
       draft!
     end
   end


 # geocoded_by :address
 # after_validation :geocode

 # カテゴリーを加える
 def add_category(category)
  categories << category
 end
  # イベントに登録されているカテゴリーの削除
 def delete_category(category)
   event_categories.find_by(category: category.id).destroy
 end
 # イベントにそのカテゴリーが含まれるか確認する
 def category_include?(category)
   categories.include?(category)
 end
end

app/controllers/events_controller.rb
# -*- encoding : utf-8 -*-
class EventsController < ApplicationController

   before_action :authenticate_user! ,only: [:new, :create]

   before_action :set_event, only: [:toggle_status]


  def index
    @q = Event.where('started_at > ?', Date.today).ransack(params[:q])

    @events = @q.result.published.order(:started_at).page(params[:page]).per(20)

  end



  def show
    @user = current_user
    @event = Event.find(params[:id])
    @users = @event.users
    @participants = User.where(id: @event.users)
    @user_event = UserEvent.find_by(event_id: @event.id, user_id: current_user.id) if current_user
    @participants = User.where(id: @users.name)
    @address = @event.address



    @hash = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.lat
      marker.lng event.lon
      marker.infowindow event.address
    end

  end

  def new
    @event = Event.new
    @categories = Category.all
  end

  def create
    @categories = Category.all
    @event = Event.new(status: :"published")
    @event = Event.new(event_params)
    @event.adminUser = current_user.id
    categories = Category.where(event_category_name_params)
    if @event.save
      categories.each do |c|
        @event.add_category(c)
      end
      flash[:success] ="作成しました"
      redirect_to @event
    else
      flash[:info] = "作成できませんでした"
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "更新しました"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def search
    @q = Event.where('started_at > ?', Date.today).ransack(params[:q])
    @events = @q.result.order(:started_at).page(params[:page]).per(20)

  end

  def confirm#下書きアクションのメソッド
    @events = Event.draft.order("created_at DESC")
  end

  def toggle_status#下書きdraftか、公開publishedを判断するメソッド、eventモデルに書いてあります
    @event.toggle_status!
    redirect_to @event, notice: '公開しました'
  end



  def destroy
    @event = Event.find(params[:id])
    @event.delete
    redirect_to confirm_events_path
    flash[:info] = "削除しました"

  end


  private
    def event_params
      params.require(:event).permit(:title, :location,:address,:lat,:lon,:description, :started_at, :ended_at,:status)
    end

    def event_category_name_params
      # params.require(:event).permit(:category)
      params.require(:category).permit(:name)
    end

    def set_event
      @event = Event.find(params[:id] || params[:event_id])
    end


end

app/helpers/events_helper.rb
# -*- encoding : utf-8 -*-
module EventsHelper
end

app/views/events/confirm.html.erb
<div class="events">
  <% last_date = nil  %>
  <% @events.each do |event| %>
    <% event_date =  event.started_at.to_date  %>
    <% if event_date != last_date  %>
      <div class="date_bar">
        <%= l(event_date, format: :long)  %>
      </div>
      <% end %>
      <% last_date = event_date  %>
    <div class="event">
      <div class="event_image">
        <%= link_to(event_path(event)) do %>
          <% if event.image  %>
            <%= image_tag event.image, width: "220px", height: "130xp"  %>
          <% elsif event.site %>
            <div class="site_logo">
              <% if event.site == "doorkeeper" %>
                <%= image_tag "doorkeeper.png", width: "140px", height: "30px" %>
              <% elsif event.site == "connpass" %>
                <%= image_tag("connpass.png", width: "120px", height: "40px") %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="event_detail">
        <%= link_to "#{event.title}",event_path(event), class: "event_title" %>
        <div class="event_site">
        </div>
        <div class="event_time">
          <%= l(event.started_at, format: :just_time) %><span>~</span>
        </div>
        <div class="event_address">
          <%= icon "fas", "map-marker-alt" %><%= event.location  %>
        </div>
        <div class="event_owner">
          <p><%= event.owner %></p>
        </div>
      </div>
      <%=link_to "編集", edit_event_path(event)%>
      <%= link_to "削除", event_path(event), method: :delete %>
      <p>

  <%= link_to '公開', event_toggle_status_path(event), method: :patch %>
</p>
    </div>

  <% end  %>

</div>
<div class="side_content">
</div>

app/views/events/edit.html.erb
<div class="container">
  <div class="event-form-wrapper">
    <% if @event.errors.any? %>
      <% @event.errors.full_messages.each do |message| %>
       <div class="form-error">
        <%= message %>
       </div>
      <% end %>
    <% end %>
    <%= form_with model: @event ,local: true do |form| %>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, placeholder: "タイトル", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :location %>
        <%= form.text_field :location, placeholder: "会場", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, placeholder: "住所", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :started_at %>
        <%= form.datetime_select :started_at, {} %>
      </div>
      <div class="form-group">
        <%= form.label :ended_at %>
        <%= form.datetime_select :ended_at, {} %>
      </div>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, placeholder: "詳細", class: "form-control" %>
      </div>


      <select name="event[status]" id="event_status">
        <option selected="selected" value="draft">下書きとして保存する</option>
        <option value="published">公開する</option>
      </select>
      <%= form.submit "編集する", class: "btn btn-info" %>
    <% end %>


  </div>
</div>

app/views/events/index.html.erb
<div class="home-wrapper">
  <div class="home-container">


<div class="event_wrapper">
  <div class="container">
    <div class="main_content">
      <div class="searchbox">
        <%= search_form_for(@q, url:search_path) do |f| %>
          <%= f.text_field :title_cont ,placeholder: 'イベント名を入力...' %>
          <%= f.submit "検索" , class: 'search-btn'%>
        <% end %>
      </div>
      <div id="calendar"></div>
      <div class="events">
        <% last_date = nil  %>
        <% @events.each do |event| %>
          <% event_date =  event.started_at.to_date  %>
          <% if event_date != last_date  %>
            <div class="date_bar">
              <%= l(event_date, format: :long)  %>
            </div>
            <% end %>
            <% last_date = event_date  %>
          <div class="event">
            <div class="event_image">
              <%= link_to(event_path(event)) do %>
                <% if event.image  %>
                  <%= image_tag event.image, width: "220px", height: "130xp"  %>
                <% elsif event.site %>
                  <div class="site_logo">
                    <% if event.site == "doorkeeper" %>
                      <%= image_tag "doorkeeper.png", width: "140px", height: "30px" %>
                    <% elsif event.site == "connpass" %>
                      <%= image_tag("connpass.png", width: "120px", height: "40px") %>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="event_detail">
              <%= link_to "#{event.title}",event_path(event), class: "event_title" %>
              <div class="event_site">
              </div>
              <div class="event_time">
                <%= l(event.started_at, format: :just_time) %><span>~</span>
              </div>
              <div class="event_address">
                <%= icon "fas", "map-marker-alt" %><%= event.location  %>
              </div>
              <div class="event_owner">
                <p><%= event.owner %></p>
                
              </div>
            </div>
          </div>
        <% end  %>
      </div>
      <div class="side_content">
      </div>
    </div>
  </div>
  <%= paginate @events  %>

app/views/events/new.html.erb
<div class="container">
  <div class="event-form-wrapper">
    <% if @event.errors.any? %>
      <% @event.errors.full_messages.each do |message| %>
       <div class="form-error">
        <%= message %>
       </div>
      <% end %>
    <% end %>
    <%= form_with model: @event ,local: true do |form| %>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, placeholder: "タイトル", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :location %>
        <%= form.text_field :location, placeholder: "会場", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :started_at %>
        <br>
        <%= form.datetime_select :started_at, {} %>
        <%= form.label :address %>
        <%= form.text_field :address, placeholder: "住所", class: "form-control" %>
      </div>


      <div class="form-group">
        <%= form.label :ended_at %>
        <br>
        <%= form.label :started_at,"開始時間" %>
        <%= form.datetime_select :started_at, {},:default => Time.now,
                :order => [:day, :month, :year,:hour,:minutes],
                :start_year => Time.now.year,
                :end_year => Time.now.year + 3,
                :id => 'started_at' %>
      </div>
      <div class="form-group">
        <%= form.label :ended_at,"終了時間" %>
        <%= form.datetime_select :ended_at, {} %>
      </div>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, placeholder: "詳細", class: "form-control" %>
      </div>
      <div class="form-group">
          <%= form.fields_for :category do |c| %>
            <%= c.label 'カテゴリー', :category %>
            <br>
            <%= select :category, :name, Category.all.map { |category| category.name }, {include_blank: '選択して下さい', class: 'mySelect2',  multiple: true } %>
          <% end %>
      </div>
      <select name="event[status]" id="event_status">
        <option selected="selected" value="draft">下書きとして保存する</option>
        <option value="published">公開する</option>
      </select>
      <%= form.submit "イベント作成", class: "btn btn-info" %>
    <% end %>


  </div>
</div>

app/views/events/search.html.erb
<div class="event_wrapper">
  <div class="container">
    <div class="main_content">
      <div class="search_result">
        <% if @events.present? %>
          <p>検索結果が<%= @events.total_count %>件表示されています。</p>
        <% else %>
          <p>検索結果が見つかりませんでした。</p>
        <% end %>
      </div>
      <div class="events">
        <% last_date = nil  %>
        <% @events.each do |event| %>
          <% event_date =  event.started_at.to_date  %>
          <% if event_date != last_date  %>
            <div class="date_bar">
              <%= l(event_date, format: :long)  %>
            </div>
            <% end %>
            <% last_date = event_date  %>
          <div class="event">
            <div class="event_image">
              <%= link_to(event_path(event)) do %>
                <% if event.image  %>
                  <%= image_tag event.image, width: "220px", height: "130xp"  %>
                <% elsif event.site %>
                  <div class="site_logo">
                    <% if event.site == "doorkeeper" %>
                      <%= image_tag "doorkeeper.png", width: "140px", height: "30px" %>
                    <% elsif event.site == "connpass" %>
                      <%= image_tag("connpass.png", width: "120px", height: "40px") %>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="event_detail">
              <%= link_to "#{event.title}",event_path(event), class: "event_title" %>
              <div class="event_site">
              </div>
              <div class="event_time">
                <%= l(event.started_at, format: :just_time) %><span>~</span>
              </div>
              <div class="event_address">
                <%= icon "fas", "map-marker-alt" %><%= event.location  %>
              </div>
              <div class="event_owner">
                <p><%= event.owner %></p>
              </div>
            </div>
          </div>
        <% end  %>
      </div>
      <div class="side_content">
      </div>
    </div>
  </div>
  <%= paginate @events  %>
 

app/views/events/show.html.erb
<div class="eventDetails_wrapper">
  <div class="eventDetails_left">
    <div class="eventDetails_title">
      <div class="eventDetails_title_date">
        <% event_date =  @event.started_at.to_date  %>
        <p class="month"><%= l(event_date, format: :just_month) %></p>
        <p class="day"><%= l(event_date, format: :just_date) %></p>
      </div>
      <h2 class="event_show_title">
        <%= @event.title %>
      </h2>
      <% if @event.image %>
        <div class="thumbnail" style="background-image: url(<%= @event.image %>)"></div>
      <% elsif @event.site == "doorkeeper" %>
        <div class="thumbnail">
          <%= image_tag("doorkeeper.png", style: "margin: 104px auto", width: "360px") %>
        </div>
      <% elsif @event.site == "connpass" %>
        <div class="thumbnail">
          <%= image_tag("connpass.png", style: "margin: 71px auto") %>
        </div>
      <% end %>
    </div>

    <div class="eventDetails_detail">
      <h2>イベント詳細</h2>
      <div class="eventDetails_detail_text">
        <% if @event.site %>
          <div class="event_detail_btn">
            <%= link_to "詳細を確認する", @event.url %>
          </div>
        <% else %>
          <%= markdown(@event.description).html_safe %>
        <% end %>
      </div>
    </div>

    <% if @event.categories %>
      <table class="table table-bordered">
        <tr>
          <% @event.categories.each do |category| %>
            <td><%= link_to category.name, category_path(category.name) %></td>
          <% end %>
        </tr>
      </table>
    <% end %>


    <div class="eventDetails_document">
      <h2>イベント資料</h2>
      <div class="eventDetails_links">
        <div class="eventDetails_links_item">
          <a href="#"><p><i class="material-icons">folder</i>Rails_tutorial.zip</p></a>
        </div>
        <div class="eventDetails_links_item">
          <a href="#"><p><i class="material-icons">folder</i>Rails_devise.zip</p></a>
        </div>
      </div>
    </div>
  </div>

  <div class="eventDetails_right">
    <div class="eventDetails_location">
      <h3><%= icon "fas", "map-marker-alt", class: "mr-2" %>会場</h3>
      <p class="event_location"><%= @event.location %></p>
      <div id="map">
        <script>
          handler = Gmaps.build("Google");
          handler.buildMap({provider: {},internal: {id: 'map'}},function(){
            markers = handler.addMarkers(<%=raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            handler.getMap().setZoom(17);
          });
        </script>
      </div>
    </div>

    <div class="eventDetails_application">
      <div class="eventDetails_application_state">
        <p>開催前</p>
      </div>
      <p><%= @event.started_at.to_s(:date) %></p>
      <p><span><%= @event.started_at.to_s(:time_jp) %></span>～<%= @event.ended_at.to_s(:time_jp) %></p>
      <% if @user_event %>
          <%= button_to "イベントの参加を取り消す", {controller: 'user_events', action: 'destroy'},
                                                { method: :delete, params: { event_id: @event.id } } %>
      <% else %>
　　　　　　<%= button_to "イベントに参加する", {controller: 'user_events', action: 'create'},
                                           { method: :post, params: { event_id: @event.id } } %>
      <% end %>
    </div>

    <div class="eventDetails_owner">
      <h2>運営</h2>
      <div class="eventDetails_owner_main">
        <p>株式会社Gude</p>
        <img src="logo.png" alt="">
        <a href="#">https://gude.jp</a>
      </div>
    </div>

    <div class="eventDetails_participant">
      <h2>参加者</h2>
      <% if @event.users %>
        <%  @event.users.each do |user| %>
          <div class="eventDetails_participant_itemWrapper">
            <div class="eventDetails_participant_item">
              <img src=<%=user.image%> alt="">
              <p><%= user.name %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>

</div>